export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  PAID = 'PAID',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SHIPPED = 'SHIPPED',
  CANCELLED = 'CANCELLED',
}

